/** Peruvian universities and institutes suggested in the application form; applicants can still type any other name. */
export const UNIVERSITIES: readonly (readonly [name: string, acronym: string])[] = [
  ['Universidad Nacional de Ingeniería', 'UNI'],
  ['Universidad Nacional Mayor de San Marcos', 'UNMSM'],
  ['Universidad Nacional Agraria La Molina', 'UNALM'],
  ['Universidad Nacional Federico Villarreal', 'UNFV'],
  ['Universidad Nacional del Callao', 'UNAC'],
  ['Universidad Nacional de Educación Enrique Guzmán y Valle', 'UNE'],
  ['Universidad Nacional Tecnológica de Lima Sur', 'UNTELS'],
  ['Universidad Nacional José Faustino Sánchez Carrión', 'UNJFSC'],
  ['Universidad Nacional de Barranca', 'UNAB'],
  ['Universidad Nacional de Cañete', 'UNDC'],
  ['Universidad Nacional San Luis Gonzaga', 'UNICA'],
  ['Universidad Nacional de San Agustín de Arequipa', 'UNSA'],
  ['Universidad Nacional de San Antonio Abad del Cusco', 'UNSAAC'],
  ['Universidad Nacional de Trujillo', 'UNT'],
  ['Universidad Nacional Pedro Ruiz Gallo', 'UNPRG'],
  ['Universidad Nacional de Piura', 'UNP'],
  ['Universidad Nacional de Frontera', 'UNF'],
  ['Universidad Nacional de Tumbes', 'UNTUMBES'],
  ['Universidad Nacional de Cajamarca', 'UNC'],
  ['Universidad Nacional de Jaén', 'UNJ'],
  ['Universidad Nacional Autónoma de Chota', 'UNACH'],
  ['Universidad Nacional del Santa', 'UNS'],
  ['Universidad Nacional Santiago Antúnez de Mayolo', 'UNASAM'],
  ['Universidad Nacional del Centro del Perú', 'UNCP'],
  ['Universidad Nacional Daniel Alcides Carrión', 'UNDAC'],
  ['Universidad Nacional Hermilio Valdizán', 'UNHEVAL'],
  ['Universidad Nacional Agraria de la Selva', 'UNAS'],
  ['Universidad Nacional de Huancavelica', 'UNH'],
  ['Universidad Nacional de San Cristóbal de Huamanga', 'UNSCH'],
  ['Universidad Nacional José María Arguedas', 'UNAJMA'],
  ['Universidad Nacional Micaela Bastidas de Apurímac', 'UNAMBA'],
  ['Universidad Nacional del Altiplano', 'UNA Puno'],
  ['Universidad Nacional de Juliaca', 'UNAJ'],
  ['Universidad Nacional Jorge Basadre Grohmann', 'UNJBG'],
  ['Universidad Nacional de Moquegua', 'UNAM'],
  ['Universidad Nacional de la Amazonía Peruana', 'UNAP'],
  ['Universidad Nacional de San Martín', 'UNSM'],
  ['Universidad Nacional de Ucayali', 'UNU'],
  ['Universidad Nacional Amazónica de Madre de Dios', 'UNAMAD'],
  ['Universidad Nacional Toribio Rodríguez de Mendoza de Amazonas', 'UNTRM'],
  ['Universidad Nacional Intercultural de la Amazonía', 'UNIA'],
  ['Universidad Nacional Autónoma de Huanta', 'UNAH'],
  ['Universidad Nacional de Música', 'UNM'],
  ['Pontificia Universidad Católica del Perú', 'PUCP'],
  ['Universidad Peruana Cayetano Heredia', 'UPCH'],
  ['Universidad del Pacífico', 'UP'],
  ['Universidad de Lima', 'ULIMA'],
  ['Universidad de Piura', 'UDEP'],
  ['Universidad de Ingeniería y Tecnología', 'UTEC'],
  ['Universidad Peruana de Ciencias Aplicadas', 'UPC'],
  ['Universidad San Ignacio de Loyola', 'USIL'],
  ['Universidad ESAN', 'ESAN'],
  ['Universidad Científica del Sur', 'UCSUR'],
  ['Universidad de San Martín de Porres', 'USMP'],
  ['Universidad Ricardo Palma', 'URP'],
  ['Universidad Tecnológica del Perú', 'UTP'],
  ['Universidad Privada del Norte', 'UPN'],
  ['Universidad César Vallejo', 'UCV'],
  ['Universidad Continental', 'UC'],
  ['Universidad Peruana Unión', 'UPeU'],
  ['Universidad Inca Garcilaso de la Vega', 'UIGV'],
  ['Universidad Femenina del Sagrado Corazón', 'UNIFÉ'],
  ['Universidad Antonio Ruiz de Montoya', 'UARM'],
  ['Universidad Católica Sedes Sapientiae', 'UCSS'],
  ['Universidad Marcelino Champagnat', 'UMCH'],
  ['Universidad Le Cordon Bleu', 'ULCB'],
  ['Universidad de Ciencias y Artes de América Latina', 'UCAL'],
  ['Universidad de Ciencias y Humanidades', 'UCH'],
  ['Universidad Peruana de Ciencias e Informática', 'UPCI'],
  ['Universidad Autónoma del Perú', 'UA'],
  ['Universidad Privada Norbert Wiener', 'UWIENER'],
  ['Universidad María Auxiliadora', 'UMA'],
  ['Universidad Jaime Bausate y Meza', 'UJBM'],
  ['Universidad Tecnológica de Lima Sur', 'UTLS'],
  ['Universidad Católica San Pablo', 'UCSP'],
  ['Universidad Católica de Santa María', 'UCSM'],
  ['Universidad La Salle', 'ULASALLE'],
  ['Universidad Andina del Cusco', 'UAC'],
  ['Universidad Andina Néstor Cáceres Velásquez', 'UANCV'],
  ['Universidad Privada Antenor Orrego', 'UPAO'],
  ['Universidad Católica Santo Toribio de Mogrovejo', 'USAT'],
  ['Universidad Señor de Sipán', 'USS'],
  ['Universidad de Huánuco', 'UDH'],
  ['Universidad Peruana Los Andes', 'UPLA'],
  ['Universidad Católica Los Ángeles de Chimbote', 'ULADECH'],
  ['Universidad San Pedro', 'USP'],
  ['Universidad Privada de Tacna', 'UPT'],
  ['Universidad José Carlos Mariátegui', 'UJCM'],
  ['Universidad Privada San Juan Bautista', 'UPSJB'],
  ['Universidad Alas Peruanas', 'UAP'],
  ['Universidad Científica del Perú', 'UCP'],
  ['Universidad Privada de Huancayo Franklin Roosevelt', 'UROOSEVELT'],
  ['Universidad Tecnológica de los Andes', 'UTEA'],
  ['Servicio Nacional de Adiestramiento en Trabajo Industrial', 'SENATI'],
  ['Tecsup', 'TECSUP'],
  ['Instituto Cibertec', 'CIBERTEC'],
  ['Instituto IDAT', 'IDAT'],
  ['Toulouse Lautrec', 'TLS'],
  ['Instituto San Ignacio de Loyola', 'ISIL'],
  ['Instituto Certus', 'CERTUS'],
  ['Instituto Zegel', 'ZEGEL'],
  ['Instituto SISE', 'SISE'],
];
